apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: "test@test.com"
        privateKeySecretRef: # used by LetsEncrypt, not associated with k8s secret
            name: letsencrypt-prod
        solvers:
            - http01:
                  ingress:
                      class: nginx
